# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "2.68.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "0e858f01-2bdc-403e-bfe7-f73d90bdd5d4"

default_platform :android

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :internal do

# build the release variant
  	#gradle(
   #task: 'assemble',
   #build_type: 'Release'
#)

  	# upload to Google Play
  	supply(track: "internal",
  		apk:"/Users/dilip/pden/app/release/app-release.apk")
end